version: '3.9' 

services:
  app:
    depends_on:
      - db
    links:
      - db
    build:
      context: .
    env_file:
      .env
    ports:
      - ${APP_PORT}:${APP_PORT} 
    volumes:
      - .:/app
      - notused:/app/node_modules
    networks:
      internal:
      shared:
        aliases:
          - "${APP_MAIN_ROUTE}"

  db:
    image: mariadb:10.8
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    ports:
    - ${MYSQL_TCP_PORT}:3306
    networks:
      internal:

volumes:
  db:
  notused:

networks:
  internal:
  shared: