version: '3.9' 

services:
  app:
    depends_on:
      - db
    build:
      context: .
    env_file:
      .env
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - notused:/app/node_modules

  db:
    image: mariadb:10.8
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    ports:
    - 3306:3306

volumes:
  db:
  notused:
